extern unsigned char date_time[];
extern unsigned char error_clock;
extern uint8_t on_relay;
extern long time_sec_sub;
extern tsDateTime	DateTimeCleared;
extern sin_addr My_sIP4addres,Clients_sIP4addres[];

void text(void);
void main_loop(void);
void OnLamp(void);
void OffLamp(void);
uint8_t get_digits(void);
void TestExtRAM(void);
void ClearRam(void);
void make_crc(unsigned char *p, int len);
unsigned char check_crc(unsigned char *p, int len);
void ProcesNetworkRouterTable(uint8_t * pu8Data, int16_t i16Lenght);
void TestNetworkRouterTable(void);
void TestSubTreeNodes(void);
void PrintCurrentEnergy(void);
void PrintTotalEnergy(void);
void AddCurrentEnergyInArray(void);
void PrintArrayCurrenEnergy(void);
void PrintDateTime(uint8_t * data);
void PrintIP_address(void);
uint32_t my_inet_addr(uint8_t * text);